"""Looking at a generated stroke.

A stroke is a path, an orientation at every sample and a velocity, run inside a
vial that is itself somewhere in the world; three coordinate curves do not show
that. This module draws the whole scene instead: the vial as a wireframe of its
real shape, the demonstrations behind it for context, and the spatula riding the
stroke as a rigid body carrying its own axes, so the lean of the blade and the
roll about it are visible while the stroke is scrubbed.

:func:`record_rrd` writes the scene as a `rerun <https://rerun.io>`_ recording to
open in the viewer, :func:`show` opens the viewer on it directly, and
:func:`render_mp4` draws the same scene as a two-viewpoint video, for a figure or
for a machine with no viewer to open. Several strokes can be drawn in one scene,
which is how a stroke and its constrained re-solve are compared.

Neither rerun nor matplotlib is a dependency of the rest of the package; both are
imported only when a view is actually drawn. Install them with
``pip install tplqt[viz]``.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Sequence, Tuple

import numpy as np
from scipy.spatial.transform import Rotation as R

from .frames import SPATULA_TOOL_AXIS, Frame, tool_axis_world
from .safety import SpatulaGeometry, VialGeometry
from .synthesize import Synthesis

Color = Tuple[int, int, int]

# Path colour and the lighter body colour drawn with it, one pair per stroke in
# the scene. The first two are the plain stroke and its constrained re-solve.
PALETTE: Tuple[Tuple[Color, Color], ...] = (
    ((200, 0, 0), (255, 150, 150)),
    ((0, 150, 60), (150, 230, 170)),
    ((30, 90, 200), (150, 180, 245)),
    ((200, 120, 0), (250, 200, 130)),
)
VIAL_COLOR: Color = (120, 120, 200)
DEMONSTRATION_COLOR: Color = (180, 180, 180)
CONTACT_COLOR: Color = (255, 220, 0)
VELOCITY_COLOR: Color = (0, 180, 0)
GRAVITY_COLOR: Color = (230, 230, 230)
AXIS_COLORS: Tuple[Color, Color, Color] = ((235, 60, 60), (60, 200, 60), (80, 130, 255))

# Sizes of the annotations, in metres: the contact dot, the axis triad on the
# spatula, the gravity arrow and how far to the side of the lip it is drawn.
CONTACT_RADIUS = 0.0015
AXIS_LENGTH = 0.02
GRAVITY_LENGTH = 0.03
GRAVITY_OFFSET = 0.05

# Velocity is a rate, not a length: the arrow is scaled to a visible size, so it
# reads as a direction and a relative magnitude, not as a distance.
VELOCITY_SCALE = 0.1


@dataclass
class Trajectory:
    """One stroke to draw: where the tip goes and how the spatula is held.

    Positions and velocities are in world coordinates and metres, orientations
    are xyzw quaternions of the spatula in world. ``color`` and ``body_color``
    override the colours the scene would otherwise take from :data:`PALETTE`.
    """

    position: np.ndarray
    orientation: np.ndarray
    velocity: Optional[np.ndarray] = None
    name: str = "stroke"
    color: Optional[Color] = None
    body_color: Optional[Color] = None

    def __post_init__(self):
        self.position = np.asarray(self.position, float)
        self.orientation = np.asarray(self.orientation, float)
        if self.position.ndim != 2 or self.position.shape[1] != 3:
            raise ValueError(f"position must be (T, 3), got {self.position.shape}")
        if self.orientation.shape != (len(self.position), 4):
            raise ValueError(
                f"orientation must be ({len(self.position)}, 4) to match the position, "
                f"got {self.orientation.shape}")
        if self.velocity is not None:
            self.velocity = np.asarray(self.velocity, float)
            if self.velocity.shape != self.position.shape:
                raise ValueError(
                    f"velocity must be {self.position.shape} to match the position, "
                    f"got {self.velocity.shape}")

    def __len__(self) -> int:
        return len(self.position)

    @classmethod
    def from_synthesis(cls, synthesis: Synthesis, **kwargs) -> "Trajectory":
        """A stroke generated by :func:`tplqt.synthesize`, ready to draw."""
        if synthesis.quat_world is None:
            raise ValueError("this stroke has no orientation to draw; fit the model "
                             "with orientation=True")
        return cls(synthesis.pos_world, synthesis.quat_world, synthesis.vel_world,
                   **kwargs)


@dataclass
class Scene:
    """A vial, the strokes run in it and the demonstrations behind them.

    ``vial_pose`` is the ``(position, quaternion)`` of the centre of the lip in
    world, the same pair :func:`tplqt.synthesize` is given. ``demonstrations`` are
    tip paths **in the vial frame**, so demonstrations recorded in vials that
    stood elsewhere are all drawn in the vial of this scene; ``Stroke.pos_vial``
    is exactly that. ``contact_point`` is in the vial frame too, and ``dt`` puts a
    timeline in seconds on the recording alongside the sample index.
    """

    vial_pose: Tuple[np.ndarray, np.ndarray]
    trajectories: Sequence[Trajectory]
    vial: VialGeometry = field(default_factory=VialGeometry)
    spatula: SpatulaGeometry = field(default_factory=SpatulaGeometry)
    demonstrations: Optional[Sequence[np.ndarray]] = None
    contact_point: Optional[np.ndarray] = None
    dt: Optional[float] = None
    name: str = "stroke"

    def __post_init__(self):
        position, quaternion = self.vial_pose
        self.vial_pose = (np.asarray(position, float), np.asarray(quaternion, float))
        # Kept as a list: the trajectories are walked once per sample, so a caller
        # who passes something that can only be walked once would lose them.
        self.trajectories = list(self.trajectories)
        if not self.trajectories:
            raise ValueError("a scene needs at least one trajectory to draw")
        empty = [t.name for t in self.trajectories if len(t) == 0]
        if empty:
            raise ValueError(f"a stroke with no samples cannot be drawn: {empty}")
        names = [trajectory.name for trajectory in self.trajectories]
        drawn = [entity_name(name) for name in names]
        if len(set(drawn)) != len(drawn):
            raise ValueError(f"the strokes of a scene are told apart by the names they "
                             f"are drawn under, where anything but a letter, a digit, a "
                             f"dash or an underscore becomes an underscore, and two of "
                             f"{names} come out the same")
        if self.contact_point is not None:
            self.contact_point = np.asarray(self.contact_point, float)

    @property
    def frame(self) -> Frame:
        """The vial frame, as the ``(rotation, origin)`` pair the package uses."""
        position, quaternion = self.vial_pose
        return R.from_quat(quaternion).as_matrix(), position

    @property
    def n_samples(self) -> int:
        """Length of the longest stroke in the scene."""
        return max(len(trajectory) for trajectory in self.trajectories)

    def to_world(self, points_vial) -> np.ndarray:
        """Lift points given in the vial frame into world."""
        A, b = self.frame
        return np.asarray(points_vial, float) @ A.T + b

    def colors(self, index: int, trajectory: Trajectory) -> Tuple[Color, Color]:
        """The path and body colours of the ``index``-th stroke of the scene."""
        path_color, body_color = PALETTE[index % len(PALETTE)]
        return (trajectory.color or path_color, trajectory.body_color or body_color)


def vial_wireframe(frame: Frame, vial: VialGeometry = VialGeometry(), *,
                   n_azimuth: int = 48, n_rings: int = 3, n_struts: int = 8):
    """Line strips drawing the inside of the vial in world coordinates.

    The vial is drawn as it is modelled: a ring at the lip, a conical shoulder
    opening out to the body radius, and a cylinder down to ``vial.length``. Three
    cross sections mark the shoulder, ``n_rings`` more the body below it, and
    ``n_struts`` lines run down the wall from the lip to the bottom.
    """
    A, b = frame
    into = -A[:, 2]
    e1, e2 = A[:, 0], A[:, 1]
    angle = np.linspace(0.0, 2.0 * np.pi, n_azimuth)
    circle = np.outer(np.cos(angle), e1) + np.outer(np.sin(angle), e2)

    shoulder, length = vial.shoulder_length, vial.length
    strips = []
    for depth in np.linspace(0.0, shoulder, 3):
        fraction = depth / shoulder if shoulder > 0 else 1.0
        radius = vial.lip_radius + (vial.body_radius - vial.lip_radius) * fraction
        strips.append(b + depth * into + radius * circle)
    for depth in np.linspace(shoulder, length, n_rings + 1)[1:]:
        strips.append(b + depth * into + vial.body_radius * circle)

    # The last azimuth closes the circle onto the first, so it carries no strut.
    for k in np.linspace(0, n_azimuth - 1, n_struts + 1)[:-1].astype(int):
        strips.append(np.array([b + vial.lip_radius * circle[k],
                                b + shoulder * into + vial.body_radius * circle[k],
                                b + length * into + vial.body_radius * circle[k]]))
    return strips


def blade_in_spatula_frame(spatula: SpatulaGeometry = SpatulaGeometry()) -> np.ndarray:
    """The blade as a segment in the spatula's own frame, tip first.

    The spatula pose the model carries is the pose of the tip, and the blade runs
    back from there against the tool axis; drawing it in the spatula frame lets
    the pose of each sample move it.
    """
    return np.array([np.zeros(3), -spatula.length * SPATULA_TOOL_AXIS])


def clip_to_box(start, end, lower, upper) -> Optional[np.ndarray]:
    """The part of a segment that lies inside an axis-aligned box.

    Returns the two endpoints of the piece inside, or ``None`` if the segment
    misses the box entirely. Matplotlib draws a three-dimensional line past the
    edges of its axes, so the blade -- which is twice as long as the vial and
    mostly outside the view -- is cut to the box before it is drawn.
    """
    start, end = np.asarray(start, float), np.asarray(end, float)
    direction = end - start
    first, last = 0.0, 1.0
    for axis in range(3):
        if abs(direction[axis]) < 1e-12:
            if not lower[axis] <= start[axis] <= upper[axis]:
                return None
            continue
        near = (lower[axis] - start[axis]) / direction[axis]
        far = (upper[axis] - start[axis]) / direction[axis]
        first = max(first, min(near, far))
        last = min(last, max(near, far))
        if first > last:
            return None
    return np.array([start + first * direction, start + last * direction])


def _rerun():
    """The rerun module, with an error that names the package it installs under."""
    try:
        import rerun as rr
    except ImportError as error:
        raise ImportError("drawing a scene needs rerun, which installs under a "
                          "different name: pip install rerun-sdk") from error
    return rr


def entity_name(name: str) -> str:
    """The name a stroke is drawn under, as one component of an entity path.

    Rerun splits entity paths on slashes and keeps them printable, so anything in
    a name that is not a letter, a digit, a dash or an underscore becomes an
    underscore. Two strokes whose names come through this the same would be drawn
    as one, which :class:`Scene` refuses.
    """
    cleaned = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
    return cleaned or "stroke"


def log_scene(scene: Scene) -> None:
    """Log everything in ``scene`` to the rerun recording stream that is open.

    :func:`record_rrd` and :func:`show` open one and call this; call it directly
    to draw the scene into a recording of your own, next to whatever else it
    holds.
    """
    rr = _rerun()

    lip = scene.vial_pose[0]
    rr.log("vial", rr.LineStrips3D(vial_wireframe(scene.frame, scene.vial),
                                   colors=[VIAL_COLOR]), static=True)
    rr.log("gravity", rr.Arrows3D(origins=[lip + GRAVITY_OFFSET * np.array([1.0, 0.0, 0.0])],
                                  vectors=[[0.0, 0.0, -GRAVITY_LENGTH]],
                                  colors=[GRAVITY_COLOR], labels=["g"]), static=True)
    for index, path_vial in enumerate(scene.demonstrations or ()):
        rr.log(f"demonstrations/{index}",
               rr.LineStrips3D([scene.to_world(path_vial)],
                               colors=[DEMONSTRATION_COLOR]), static=True)
    if scene.contact_point is not None:
        rr.log("contact", rr.Points3D([scene.to_world(scene.contact_point)],
                                      colors=[CONTACT_COLOR], radii=[CONTACT_RADIUS]),
               static=True)

    blade = blade_in_spatula_frame(scene.spatula)
    base = blade[1]
    for index, trajectory in enumerate(scene.trajectories):
        path_color, body_color = scene.colors(index, trajectory)
        entity = f"strokes/{entity_name(trajectory.name)}"
        rr.log(f"{entity}/path", rr.LineStrips3D([trajectory.position],
                                                 colors=[path_color]), static=True)
        # The blade and the axes are logged once, in the spatula frame; the pose
        # logged at each sample below is what moves them.
        rr.log(f"{entity}/spatula/blade", rr.LineStrips3D([blade], colors=[body_color]),
               static=True)
        rr.log(f"{entity}/spatula/axes",
               rr.Arrows3D(origins=[base] * 3, vectors=AXIS_LENGTH * np.eye(3),
                           colors=list(AXIS_COLORS), labels=["x", "y", "z"]), static=True)

    for t in range(scene.n_samples):
        rr.set_time("sample", sequence=t)
        if scene.dt is not None:
            rr.set_time("time", duration=t * scene.dt)
        for trajectory in scene.trajectories:
            if t >= len(trajectory):
                continue
            entity = f"strokes/{entity_name(trajectory.name)}"
            rr.log(f"{entity}/spatula", rr.Transform3D(
                translation=trajectory.position[t],
                quaternion=rr.Quaternion(xyzw=trajectory.orientation[t])))
            if trajectory.velocity is not None:
                # Logged outside the spatula entity, so the pose does not turn it.
                rr.log(f"{entity}/velocity", rr.Arrows3D(
                    origins=[trajectory.position[t]],
                    vectors=[VELOCITY_SCALE * trajectory.velocity[t]],
                    colors=[VELOCITY_COLOR]))


def record_rrd(path: str, scene: Scene) -> str:
    """Write ``scene`` to ``path`` as a rerun recording.

    Open it with ``rerun <path>``; :func:`show` draws the same scene straight into
    a viewer instead.
    """
    rr = _rerun()

    rr.init(f"tplqt {scene.name}")
    log_scene(scene)
    rr.save(path)
    return path


def show(scene: Scene) -> None:
    """Open the rerun viewer on ``scene`` without writing a file."""
    rr = _rerun()

    rr.init(f"tplqt {scene.name}", spawn=True)
    log_scene(scene)


def render_mp4(path: str, scene: Scene, *, fps: int = 20, max_frames: int = 120,
               figsize: Tuple[float, float] = (12.0, 6.0)) -> str:
    """Draw ``scene`` as a two-viewpoint animation and write it to ``path``.

    Needs matplotlib and ffmpeg. The two viewpoints are a general one and a view
    straight down the bore, which between them show the depth the stroke reaches
    and how far across the mouth it goes. At most ``max_frames`` samples are
    drawn, spread evenly along the longest stroke.
    """
    from matplotlib.animation import FFMpegWriter, FuncAnimation
    from matplotlib.backends.backend_agg import FigureCanvasAgg
    from matplotlib.figure import Figure

    strips = vial_wireframe(scene.frame, scene.vial)
    blade_length = scene.spatula.length
    demonstrations = [scene.to_world(p) for p in (scene.demonstrations or ())]
    drawn = [(trajectory,) + tuple(np.asarray(c) / 255.0
                                   for c in scene.colors(index, trajectory))
             for index, trajectory in enumerate(scene.trajectories)]
    tool = {trajectory.name: np.atleast_2d(tool_axis_world(trajectory.orientation))
            for trajectory, _, _ in drawn}

    step = max(1, int(np.ceil(scene.n_samples / max_frames)))
    drawn_samples = np.arange(0, scene.n_samples, step)
    # The frame holds the vial and the strokes; the blade is longer than both and
    # is cut to the frame rather than shrinking everything else.
    extent = np.vstack([t.position for t in scene.trajectories] + strips)
    centre = (extent.min(0) + extent.max(0)) / 2.0
    radius = (extent.max(0) - extent.min(0)).max() / 2.0 * 1.05
    lower, upper = centre - radius, centre + radius
    contact = (None if scene.contact_point is None
               else scene.to_world(scene.contact_point))

    # The figure is built and drawn without pyplot, so rendering a video does not
    # take over the backend of whoever called.
    figure = Figure(figsize=figsize)
    FigureCanvasAgg(figure)
    axes = [figure.add_subplot(1, 2, k + 1, projection="3d") for k in range(2)]
    # One general view, and one looking straight into the mouth along the bore,
    # where the mouth is a circle and it is plain how far across it the stroke
    # reaches.
    bore = scene.frame[0][:, 2]
    viewpoints = [((20.0, -60.0), "perspective"),
                  ((float(np.degrees(np.arcsin(np.clip(bore[2], -1.0, 1.0)))),
                    float(np.degrees(np.arctan2(bore[1], bore[0])))), "along the bore")]

    def draw(index):
        t = int(drawn_samples[index])
        for axis, ((elevation, azimuth), title) in zip(axes, viewpoints):
            axis.cla()
            axis.set_title(title)
            axis.set_xlim(centre[0] - radius, centre[0] + radius)
            axis.set_ylim(centre[1] - radius, centre[1] + radius)
            axis.set_zlim(centre[2] - radius, centre[2] + radius)
            axis.view_init(elev=elevation, azim=azimuth)
            axis.set_box_aspect((1.0, 1.0, 1.0))
            axis.locator_params(nbins=4)
            axis.set_xlabel("x")
            axis.set_ylabel("y")
            axis.set_zlabel("z")
            for strip in strips:
                axis.plot(*strip.T, color=np.asarray(VIAL_COLOR) / 255.0, lw=0.8)
            for demonstration in demonstrations:
                axis.plot(*demonstration.T,
                          color=np.asarray(DEMONSTRATION_COLOR) / 255.0, lw=0.6)
            if contact is not None:
                axis.scatter(*contact, color=np.asarray(CONTACT_COLOR) / 255.0, s=20,
                             edgecolor="k", linewidth=0.5)
            for trajectory, path_color, body_color in drawn:
                last = min(t, len(trajectory) - 1)
                axis.plot(*trajectory.position[:last + 1].T, color=path_color, lw=1.6)
                tip = trajectory.position[last]
                base = tip - blade_length * tool[trajectory.name][last]
                blade = clip_to_box(tip, base, lower, upper)
                if blade is not None:
                    axis.plot(*blade.T, color=body_color, lw=2.8)
                if trajectory.velocity is not None:
                    axis.quiver(*tip, *(VELOCITY_SCALE * trajectory.velocity[last]),
                                color=np.asarray(VELOCITY_COLOR) / 255.0, lw=2)
        figure.suptitle(f"sample {t} of {scene.n_samples - 1}")

    animation = FuncAnimation(figure, draw, frames=len(drawn_samples), blit=False)
    animation.save(path, writer=FFMpegWriter(fps=fps))
    return path
